### ISSUE TITLE
Watchdog interrupt error

### ISSUE THREAD

**Issue by wifwucite** [lask/toit-hs-sr04#1]
When I run the example, I see this output:

The distance is: 3 cm
The distance is: 69 cm
The distance is: 5 cm
The distance is: 2 cm
The distance is: 3 cm
The distance is: 4 cm
2022-03-05T18:44:21.971214Z: <stack trace>
WATCHDOG INTERRUPT error.
  0: watchdog_                 <sdk>/core/exceptions.toit:202:1
  1: Driver.read_              <pkg:toit-hs-sr04>/driver.toit:91:3
  2: Driver.run_               <pkg:toit-hs-sr04>/driver.toit:47:24
  3: Driver.start.<lambda>     <pkg:toit-hs-sr04>/driver.toit:41:9

Typically I see some readings, which make sense. And then after some time the watchdog kills the program.

**Comment by lask** [comment]
That's interesting. I thought that the driver was missing a yield somewhere, but it does not look like it.

FYI Toit is not great for timing sensitive drivers like this one as the timings may be a bit off because of interruptions (the garbage collector may start) and overhead (there is a bit of overhead to every primitive call). However, I am working on support for the RMT controller supported by ESP32 which is well suited for timing sensitive applications like this one.

**Comment by lask** [comment]
Fixed by 4d27ab2e41139ed9815e0e6ba2950ab470d97019

**Comment by wifwucite** [comment]
Thank you for approving the PR so quickly. What is the RMT controller? 
By the way I have an US-100 sensor, which can act like HS-SR04, but it can also perform measurements itself and communicate via UART. Maybe I should go for that option, timing should not be an issue then.
